### ISSUE TITLE
Missing "debug" subcommand

### ISSUE THREAD

**Issue by moritzheiber** [jodosha/vim-godebug#1]
Brilliant plugin, thank you for making it available. However, when trying to get it to run, and having all the prerequisites installed as mentioned in the README.md, I'm getting the following after having set a breakpoint and running `:GoDebug`:

```
vim-go: go: unknown subcommand "debug"
```

If I manually run `go debug` I get the same error message. Is there anything else I need to install before being able to use the plugin?

**Comment by meinside** [comment]
Hi, I'm suffering from a similar issue here.

- [x] Go installed,
- [x] Vim/Nvim installed,
- [x] vim-go installed, (using vundle)
- [x] :GoInstallBinaries finished,
- [x] Delve is installed with `go get`
- [x] (don't know if it is essential, but) `golang.org/x/debug` installed with `go get`

When trying `:GoDebug` in vim, I see
```
Error detected while processing function godebug#debug[19]..go#jobcontrol#Spawn[4]..<SNR>95_spawn:
E117: Unknown function: jobstart
E15: Invalid expression: jobstart(argv, job)
```

and in nvim,
```
vim-go: go: unknown subcommand "debug"
```

Is there anything else I should do?

**Comment by jodosha** [comment]
@moritzheiber @meinside Hi, please note that this won't work yet with Vim (I use NeoVim). I've plenty of OSS work to do, and won't support actively this plugin (as stated in the README).

If you find a solution, please open a PR and I'll be happy to merge it.

---

That being said, `go debug` is not necessary and I don't know why it's called in the first place. The only syscall is `delve debug <args>`.

**Comment by moritzheiber** [comment]
@jodosha Where does it call delve though? I don't see that anywhere in the code.

**Comment by meinside** [comment]
@moritzheiber It's called in https://github.com/jodosha/vim-godebug/blob/master/plugin/godebug.vim#L69 and https://github.com/jodosha/vim-godebug/blob/master/plugin/godebug.vim#L71

I don't get why, but adding `let g:go_term_enabled=1` in my nvim's config file fixed it, FYI.
