### ISSUE TITLE
Error detected while processing function godebug#debug

### ISSUE THREAD

**Issue by olebedev** [jodosha/vim-godebug#3]
I've got this output while calling `GoDebug`:

```
Error detected while processing function godebug#debug[19]..go#jobcontrol#Spawn[4]..<SNR>206_spawn:
line   49:
E117: Unknown function: jobstart
E15: Invalid expression: jobstart(argv, job)
```
What I am doing wrong?

---
Steps to reproduce:

- toggle breakpoint
- call `GoDebug`

Dlv installed via `brew`, `vim-godebug` and all other the plugins installed and updated via `Vundle.vim`

**Comment by jodosha** [comment]
@olebedev Hi, please check if this solves your problem: https://github.com/jodosha/vim-godebug#troubleshooting

**Comment by olebedev** [comment]
It definitely helps!

ср, 15 февр. 2017 г. в 19:06, Luca Guidi <notifications@github.com>:
